export const OBTER_PROJETOS = 'OBTER_PROJETOS';
export const CADASTRAR_PROJETO = 'CADASTRAR_PROJETO';
export const EDITAR_PROJETO = 'EDITAR_PROJETO';
export const DELETAR_PROJETO = 'EXCLUIR_PROJETO';
export const OBTER_TAREFAS = 'OBTER_TAREFAS';